/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CoCreationRouteImport } from './routes/co-creation'
import { Route as InquiryRouteImport } from './routes/inquiry'
import { Route as RecordRouteImport } from './routes/record'
import { Route as WritingsRouteImport } from './routes/writings'
import { Route as InstrumentsIndexRouteImport } from './routes/instruments.index'
import { Route as InstrumentsSlugRouteImport } from './routes/instruments.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CoCreationRoute = CoCreationRouteImport.update({
  id: '/co-creation',
  path: '/co-creation',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiryRoute = InquiryRouteImport.update({
  id: '/inquiry',
  path: '/inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordRoute = RecordRouteImport.update({
  id: '/record',
  path: '/record',
  getParentRoute: () => rootRouteImport,
} as any)
const WritingsRoute = WritingsRouteImport.update({
  id: '/writings',
  path: '/writings',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrumentsIndexRoute = InstrumentsIndexRouteImport.update({
  id: '/instruments/',
  path: '/instruments/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrumentsSlugRoute = InstrumentsSlugRouteImport.update({
  id: '/instruments/$slug',
  path: '/instruments/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/co-creation': typeof CoCreationRoute
  '/inquiry': typeof InquiryRoute
  '/record': typeof RecordRoute
  '/writings': typeof WritingsRoute
  '/instruments/$slug': typeof InstrumentsSlugRoute
  '/instruments/': typeof InstrumentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/co-creation': typeof CoCreationRoute
  '/inquiry': typeof InquiryRoute
  '/record': typeof RecordRoute
  '/writings': typeof WritingsRoute
  '/instruments/$slug': typeof InstrumentsSlugRoute
  '/instruments': typeof InstrumentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/co-creation': typeof CoCreationRoute
  '/inquiry': typeof InquiryRoute
  '/record': typeof RecordRoute
  '/writings': typeof WritingsRoute
  '/instruments/$slug': typeof InstrumentsSlugRoute
  '/instruments/': typeof InstrumentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/co-creation'
    | '/inquiry'
    | '/record'
    | '/writings'
    | '/instruments/$slug'
    | '/instruments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/co-creation'
    | '/inquiry'
    | '/record'
    | '/writings'
    | '/instruments/$slug'
    | '/instruments'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/co-creation'
    | '/inquiry'
    | '/record'
    | '/writings'
    | '/instruments/$slug'
    | '/instruments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CoCreationRoute: typeof CoCreationRoute
  InquiryRoute: typeof InquiryRoute
  RecordRoute: typeof RecordRoute
  WritingsRoute: typeof WritingsRoute
  InstrumentsSlugRoute: typeof InstrumentsSlugRoute
  InstrumentsIndexRoute: typeof InstrumentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/co-creation': {
      id: '/co-creation'
      path: '/co-creation'
      fullPath: '/co-creation'
      preLoaderRoute: typeof CoCreationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiry': {
      id: '/inquiry'
      path: '/inquiry'
      fullPath: '/inquiry'
      preLoaderRoute: typeof InquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record': {
      id: '/record'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/writings': {
      id: '/writings'
      path: '/writings'
      fullPath: '/writings'
      preLoaderRoute: typeof WritingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instruments/': {
      id: '/instruments/'
      path: '/instruments'
      fullPath: '/instruments/'
      preLoaderRoute: typeof InstrumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instruments/$slug': {
      id: '/instruments/$slug'
      path: '/instruments/$slug'
      fullPath: '/instruments/$slug'
      preLoaderRoute: typeof InstrumentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CoCreationRoute: CoCreationRoute,
  InquiryRoute: InquiryRoute,
  RecordRoute: RecordRoute,
  WritingsRoute: WritingsRoute,
  InstrumentsSlugRoute: InstrumentsSlugRoute,
  InstrumentsIndexRoute: InstrumentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
